/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Vue component name
 */
export type Component = string;
/**
 * List of child component ids to be placed within the Window
 */
export type Childcomponents = string[];
/**
 * Selected window item for the window
 */
export type Value = (string | number | null)[] | string | number | null;
/**
 * Show navigation arrows
 */
export type ShowArrows = boolean;
/**
 * Icon used for the “next” button if show-arrows is true
 */
export type NextIcon = string;
/**
 * Icon used for the “previous” button if show-arrows is true
 */
export type PrevIcon = string;
/**
 * Determines if the window is disabled
 */
export type Disabled = boolean | null;
/**
 * Trigger event for when to trigger a run
 */
export type Triggerevent = string;

/**
 * Window component provides the functionality for transitioning content from one pane to another
 */
export interface Window {
  component?: Component;
  childComponents?: Childcomponents;
  value?: Value;
  show_arrows?: ShowArrows;
  next_icon?: NextIcon;
  prev_icon?: PrevIcon;
  disabled?: Disabled;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
